pub mod broadcast;
pub mod crypto;
pub mod discovery;
#[cfg(feature = "host")]
pub mod listener;
#[cfg(feature = "player")]
pub mod receiver;
pub mod rtp;
pub mod session;
pub mod signaling;
pub mod signaling_server;
#[cfg(feature = "host")]
pub mod streamer;
#[cfg(feature = "host")]
pub mod udp_stream;
pub mod webrtc;

use serde::{Deserialize, Serialize};
use std::net::SocketAddr;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CandidateType {
    Lan,
    Public,
    IPv6,
    Relay,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Candidate {
    pub candidate_type: CandidateType,
    pub addr: SocketAddr,
    pub priority: u32,
}

pub const DEFAULT_PORT: u16 = 45100;
pub const CONTROL_PORT: u16 = 45101;
pub const MDNS_SERVICE_TYPE: &str = "_beacon-pulse._udp.local.";

/// Messages sent over the reliable control channel (JSON over TCP/named pipe)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ControlMessage {
    // Client → Host
    JoinRequest {
        client_id: String,
        display_name: String,
        version: String,
        /// UDP port the client is listening on for incoming video frames
        udp_port: u16,
        #[serde(default)]
        candidates: Option<Vec<Candidate>>,
        #[serde(default)]
        public_key: Option<String>,
    },

    PairingCode {
        /// base64(HMAC-SHA256(key=pairing_code, data=challenge))
        hmac: String,
    },
    RequestKeyframe,
    BitrateReport {
        /// Client-measured receive bitrate in kbps
        recv_kbps: u32,
        packet_loss_percent: f32,
        rtt_ms: u32,
    },
    InputEvent {
        event: InputMsg,
    },
    Disconnect {
        reason: String,
    },
    FileStart {
        name: String,
        size: u64,
    },
    FileChunk {
        data: String,
    },
    FileEnd,
    ListHostProcesses,
    KillHostProcess {
        pid: u32,
    },
    ListHostMonitors,
    SwitchHostMonitor {
        display_handle: isize,
    },

    // Host → Client
    JoinAccepted {
        session_id: String,
        stream_port: u16,
        permissions: Permissions,
        #[serde(default)]
        candidates: Option<Vec<Candidate>>,
        #[serde(default)]
        public_key: Option<String>,
    },
    JoinRejected {
        reason: String,
    },
    PairingRequired {
        /// base64-encoded 32-byte random challenge generated by the host.
        /// Client computes HMAC-SHA256(key=pairing_code, data=challenge) and
        /// returns it in `PairingCode { hmac }`.
        challenge: String,
    },
    StreamStarted {
        width: u32,
        height: u32,
        fps: u32,
        codec: String,
    },
    StreamStopped {
        reason: String,
    },
    PermissionsUpdated {
        permissions: Permissions,
    },
    CursorChanged {
        shape: String,
    },
    ClipboardSync {
        text: String,
    },
    HostProcessList {
        processes: Vec<ProcessInfo>,
    },
    HostProcessKilled {
        pid: u32,
        success: bool,
    },
    HostMonitorList {
        monitors: Vec<crate::capture::display_list::MonitorInfo>,
    },
    // File Manager
    BrowseDirectoryRequest {
        path: String,
    },
    DownloadFileRequest {
        path: String,
    },
    FileActionRequest {
        action: String,
        path: String,
        new_path: Option<String>,
    },
    BrowseDirectoryResponse {
        path: String,
        entries: Vec<FileEntry>,
        error: Option<String>,
    },
    DownloadFileStart {
        name: String,
        size: u64,
    },
    DownloadFileChunk {
        data: String,
    },
    DownloadFileEnd,
    FileActionResponse {
        success: bool,
        error: Option<String>,
    },
    // Stream Settings
    UpdateStreamSettings {
        fps: Option<u32>,
        scale: Option<f32>,
        bitrate_bps: Option<u32>,
    },
    // Remote Shell
    ShellStart,
    ShellInput {
        text: String,
    },
    ShellOutput {
        text: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Permissions {
    pub input_control: bool,
    pub clipboard: bool,
    pub audio: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessInfo {
    pub pid: u32,
    pub name: String,
    pub threads: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileEntry {
    pub name: String,
    pub is_dir: bool,
    pub size: u64,
    pub modified: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum InputMsg {
    MouseMove {
        x: f32,
        y: f32,
        viewport_w: u32,
        viewport_h: u32,
        #[serde(default)]
        display_id: Option<u8>,
    },
    MouseButton {
        button: u8,
        pressed: bool,
        x: f32,
        y: f32,
        viewport_w: u32,
        viewport_h: u32,
        #[serde(default)]
        display_id: Option<u8>,
    },
    MouseScroll {
        delta_x: f32,
        delta_y: f32,
    },
    KeyPress {
        vk_code: u32,
        scan_code: u32,
        pressed: bool,
        #[serde(default)]
        is_extended: bool,
    },
}

pub fn create_dual_stack_listener(port: u16) -> std::io::Result<tokio::net::TcpListener> {
    use socket2::{Domain, Protocol, Socket, Type};
    use std::net::SocketAddr;

    let ipv6_addr = SocketAddr::from(([0, 0, 0, 0, 0, 0, 0, 0], port)); // [::]:port

    // Try binding to IPv6 dual-stack
    if let Ok(socket) = Socket::new(Domain::IPV6, Type::STREAM, Some(Protocol::TCP)) {
        if socket.set_only_v6(false).is_ok() {
            if socket.set_reuse_address(true).is_ok() {
                if socket.bind(&ipv6_addr.into()).is_ok() {
                    if socket.listen(128).is_ok() {
                        let std_listener: std::net::TcpListener = socket.into();
                        if std_listener.set_nonblocking(true).is_ok() {
                            if let Ok(tokio_listener) =
                                tokio::net::TcpListener::from_std(std_listener)
                            {
                                return Ok(tokio_listener);
                            }
                        }
                    }
                }
            }
        }
    }

    // Fallback to standard IPv4 binding
    let ipv4_addr = SocketAddr::from(([0, 0, 0, 0], port)); // 0.0.0.0:port
    let socket = Socket::new(Domain::IPV4, Type::STREAM, Some(Protocol::TCP))?;
    socket.set_reuse_address(true)?;
    socket.bind(&ipv4_addr.into())?;
    socket.listen(128)?;
    let std_listener: std::net::TcpListener = socket.into();
    std_listener.set_nonblocking(true)?;
    tokio::net::TcpListener::from_std(std_listener)
}

pub fn create_dual_stack_udp_socket(port: u16) -> std::io::Result<std::net::UdpSocket> {
    use socket2::{Domain, Protocol, Socket, Type};
    use std::net::SocketAddr;

    let ipv6_addr = SocketAddr::from(([0, 0, 0, 0, 0, 0, 0, 0], port)); // [::]:port

    // Try binding to IPv6 dual-stack
    if let Ok(socket) = Socket::new(Domain::IPV6, Type::DGRAM, Some(Protocol::UDP)) {
        if socket.set_only_v6(false).is_ok() {
            if socket.set_reuse_address(true).is_ok() {
                let _ = socket.set_recv_buffer_size(2 * 1024 * 1024);
                let _ = socket.set_send_buffer_size(2 * 1024 * 1024);
                if socket.bind(&ipv6_addr.into()).is_ok() {
                    let std_sock: std::net::UdpSocket = socket.into();
                    return Ok(std_sock);
                }
            }
        }
    }

    // Fallback to standard IPv4 binding
    let ipv4_addr = SocketAddr::from(([0, 0, 0, 0], port)); // 0.0.0.0:port
    let socket = Socket::new(Domain::IPV4, Type::DGRAM, Some(Protocol::UDP))?;
    socket.set_reuse_address(true)?;
    let _ = socket.set_recv_buffer_size(2 * 1024 * 1024);
    let _ = socket.set_send_buffer_size(2 * 1024 * 1024);
    socket.bind(&ipv4_addr.into())?;
    let std_sock: std::net::UdpSocket = socket.into();
    Ok(std_sock)
}
