pub mod broadcast;
pub mod discovery;
#[cfg(feature = "host")]
pub mod listener;
#[cfg(feature = "player")]
pub mod receiver;
pub mod rtp;
pub mod session;
pub mod signaling;
pub mod webrtc;
#[cfg(feature = "host")]
pub mod streamer;
#[cfg(feature = "host")]
pub mod udp_stream;

use serde::{Deserialize, Serialize};

pub const DEFAULT_PORT: u16 = 45100;
pub const CONTROL_PORT: u16 = 45101;
pub const MDNS_SERVICE_TYPE: &str = "_beacon-pulse._udp.local.";

/// Messages sent over the reliable control channel (JSON over TCP/named pipe)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ControlMessage {
    // Client → Host
    JoinRequest {
        client_id: String,
        display_name: String,
        version: String,
        /// UDP port the client is listening on for incoming video frames
        udp_port: u16,
    },
    PairingCode {
        /// base64(HMAC-SHA256(key=pairing_code, data=challenge))
        hmac: String,
    },
    RequestKeyframe,
    BitrateReport {
        /// Client-measured receive bitrate in kbps
        recv_kbps: u32,
        packet_loss_percent: f32,
        rtt_ms: u32,
    },
    InputEvent {
        event: InputMsg,
    },
    Disconnect {
        reason: String,
    },
    FileStart {
        name: String,
        size: u64,
    },
    FileChunk {
        data: String,
    },
    FileEnd,
    ListHostProcesses,
    KillHostProcess {
        pid: u32,
    },
    ListHostMonitors,
    SwitchHostMonitor {
        display_handle: isize,
    },

    // Host → Client
    JoinAccepted {
        session_id: String,
        stream_port: u16,
        permissions: Permissions,
    },
    JoinRejected {
        reason: String,
    },
    PairingRequired {
        /// base64-encoded 32-byte random challenge generated by the host.
        /// Client computes HMAC-SHA256(key=pairing_code, data=challenge) and
        /// returns it in `PairingCode { hmac }`.
        challenge: String,
    },
    StreamStarted {
        width: u32,
        height: u32,
        fps: u32,
        codec: String,
    },
    StreamStopped {
        reason: String,
    },
    PermissionsUpdated {
        permissions: Permissions,
    },
    CursorChanged {
        shape: String,
    },
    ClipboardSync {
        text: String,
    },
    HostProcessList {
        processes: Vec<ProcessInfo>,
    },
    HostProcessKilled {
        pid: u32,
        success: bool,
    },
    HostMonitorList {
        monitors: Vec<crate::capture::display_list::MonitorInfo>,
    },
    // File Manager
    BrowseDirectoryRequest {
        path: String,
    },
    DownloadFileRequest {
        path: String,
    },
    FileActionRequest {
        action: String,
        path: String,
        new_path: Option<String>,
    },
    BrowseDirectoryResponse {
        path: String,
        entries: Vec<FileEntry>,
        error: Option<String>,
    },
    DownloadFileStart {
        name: String,
        size: u64,
    },
    DownloadFileChunk {
        data: String,
    },
    DownloadFileEnd,
    FileActionResponse {
        success: bool,
        error: Option<String>,
    },
    // Stream Settings
    UpdateStreamSettings {
        fps: Option<u32>,
        scale: Option<f32>,
        bitrate_bps: Option<u32>,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Permissions {
    pub input_control: bool,
    pub clipboard: bool,
    pub audio: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessInfo {
    pub pid: u32,
    pub name: String,
    pub threads: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileEntry {
    pub name: String,
    pub is_dir: bool,
    pub size: u64,
    pub modified: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum InputMsg {
    MouseMove {
        x: f32,
        y: f32,
        viewport_w: u32,
        viewport_h: u32,
        #[serde(default)]
        display_id: Option<u8>,
    },
    MouseButton {
        button: u8,
        pressed: bool,
        x: f32,
        y: f32,
        viewport_w: u32,
        viewport_h: u32,
        #[serde(default)]
        display_id: Option<u8>,
    },
    MouseScroll {
        delta_x: f32,
        delta_y: f32,
    },
    KeyPress {
        vk_code: u32,
        scan_code: u32,
        pressed: bool,
        #[serde(default)]
        is_extended: bool,
    },
}
