use serde::{Deserialize, Serialize};

/// Unified signaling messages exchanged over the TCP/TLS control channel
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SignalingMessage {
    /// Host registers its pairing code on signaling server (if proxying is used)
    RegisterHost {
        pairing_code: String,
    },
    /// Player registers to connect via pairing code
    RegisterPlayer {
        pairing_code: String,
    },
    /// Confirmation from the broker
    RegistrationSuccess {
        role: String,
    },
    /// Rejection from the broker
    RegistrationFailed {
        reason: String,
    },
    /// WebRTC Session Description Protocol (SDP) Offer sent by the host
    SdpOffer {
        sdp: String,
    },
    /// WebRTC Session Description Protocol (SDP) Answer returned by the player
    SdpAnswer {
        sdp: String,
    },
    /// WebRTC ICE Candidate exchanged for NAT traversal / direct connections
    IceCandidate {
        candidate: String,
        sdp_mid: Option<String>,
        sdp_m_line_index: Option<u16>,
    },
    /// Initial request from client indicating pairing is needed
    PairingRequired {
        /// Base64 challenge bytes generated by the host
        challenge: String,
    },
    /// HMAC response solved using the pairing PIN
    PairingResponse {
        /// Base64 HMAC signature
        hmac: String,
    },
    /// Disconnect request
    Disconnect {
        reason: String,
    },
}

/// Binary input layout constants for the WebRTC DataChannel.
/// Raw buffers are parsed directly using standard bit/byte offsets for performance.
pub mod binary_input {
    pub const TYPE_MOUSE_MOVE: u8 = 0x01;
    pub const TYPE_MOUSE_BUTTON_PRESS: u8 = 0x02;
    pub const TYPE_MOUSE_BUTTON_RELEASE: u8 = 0x03;
    pub const TYPE_MOUSE_SCROLL: u8 = 0x04;
    pub const TYPE_KEY_PRESS: u8 = 0x05;
    pub const TYPE_KEY_RELEASE: u8 = 0x06;

    pub const BUTTON_NONE: u8 = 0x00;
    pub const BUTTON_LEFT: u8 = 0x01;
    pub const BUTTON_RIGHT: u8 = 0x02;
    pub const BUTTON_MIDDLE: u8 = 0x04;

    pub const KEY_FLAG_STANDARD: u8 = 0x00;
    pub const KEY_FLAG_EXTENDED: u8 = 0x01;
}
